# Generated by Django 2.2.6 on 2020-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.CharField(max_length=50, unique=True, verbose_name='Currency slug'),
        ),
    ]
