# Generated by Django 2.2.6 on 2020-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_auto_20200116_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangehistory',
            old_name='issue_rate',
            new_name='issue_rate_from',
        ),
        migrations.AddField(
            model_name='exchangehistory',
            name='issue_rate_to',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Rate in usd'),
        ),
    ]
