# Generated by Django 2.2.6 on 2020-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0003_auto_20200127_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangehistory',
            name='ingoing_amount',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='From exchange amount'),
        ),
        migrations.AlterField(
            model_name='exchangehistory',
            name='outgoing_amount',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='To exchange amount'),
        ),
        migrations.AlterField(
            model_name='inputtransaction',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Transaction amount'),
        ),
        migrations.AlterField(
            model_name='outputtransaction',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Transaction amount'),
        ),
    ]
