# Generated by Django 2.2.6 on 2020-02-16 13:48

from exchanger.models import ExchangeHistory
from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    ExchangeHistory = apps.get_model('exchanger', 'ExchangeHistory')
    for exchanger in ExchangeHistory.objects.all():
        exchanger.uuid = uuid.uuid4()
        exchanger.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0006_auto_20200216_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangehistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4,
                                   editable=False,
                                   verbose_name='Internal hash'),
        ),
        migrations.RunPython(create_uuid),
    ]
