# Generated by Django 2.2.6 on 2020-02-16 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0007_exchangehistory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangehistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Internal hash'),
        ),
    ]
