# Generated by Django 2.2.6 on 2020-02-19 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0008_auto_20200216_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Internal hash for identification trx'),
        ),
        migrations.AlterField(
            model_name='outputtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Internal hash for identification trx'),
        ),
    ]
