# Generated by Django 2.2.6 on 2020-02-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0009_auto_20200219_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangehistory',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'UNKNOWN STATUS'), (1, 'NEW'), (2, 'WAITING MONEY FROM USER'), (3, 'MONEY TRANSFER IS INSUFFICIENT'), (4, 'DEPOSIT PAID'), (5, 'CREATING MONEY TRANSFER TO USER'), (6, 'WAITING TO CONFIRM OUTPUT TRANSFER'), (7, 'EXCHANGE IS DONE'), (8, 'FAILED EXCHANGE'), (9, 'RETURNING_DEPOSIT'), (10, 'DEPOSIT_RETURNED'), (11, 'CALCULATING'), (12, 'WAITING INPUT TRANSACTION HASH'), (13, 'CREATING OUTPUT TRANSACTION')], db_index=True, default=0),
        ),
    ]
